Repository RooftopAcademy/rooftend, pull requests merged in 2021-11, with the labels that each got.

#84 Feature categories documentation
  src/categories/categories.entity.ts
  src/categories/categories/controllers/categories.controller.ts
  src/categories/categories/services/categories.service.ts
Labels: size: 2

#85 Feature 43 categories relations
  src/app.module.ts
  src/categories/categories.entity.ts
Labels: size: 2

#87 Several bugfixes
  package.json
  src/account-status/account-status.module.ts
  src/brands/entities/brands.entity.ts
  src/categories/categories/controllers/categories.controller.ts
  src/categories/categories/services/categories.service.ts
  src/entity/User.ts
  src/favorites/entities/favorite.entity.ts
  src/history/controllers/history/history.controller.ts
  src/history/models/history.entity.ts
  src/history/services/history/history.service.ts
  src/index.ts
  src/notification/entities/notification.entity.ts
  src/payment-methods/payment-method.entity.ts
  src/paymentMethods/controllers/payment-method.controller.ts
  src/paymentMethods/services/payment-method.service.ts
  src/photos/models/photos.entity.ts
  src/platform/create-platform-dto.entity.ts
  src/platform/platform.entity.ts
  src/questions/controllers/questions.controller.ts
  src/questions/questions.entity.ts
  src/review/review.entity.ts
  src/stores/controller/stores.controller.ts
  src/stores/controller/stores.service.ts
  src/stores/models/stores.entity.ts
  src/stores/models/stores.interface.ts
  src/users/User.ts
  src/users/entities/user.entity.ts
Labels: size: 5

#90 Fix 89 user controller
  package-lock.json
  src/account-status/account-status.module.ts
  src/categories/categories/controllers/categories.controller.ts
  src/categories/categories/services/categories.service.ts
  src/history/models/history.entity.ts
  src/platform/controllers/platform.controller.ts
  src/platform/create-platform-dto.entity.ts
  src/stores/models/stores.entity.ts
  src/users/controllers/user.controller.ts
Labels: size: 3

#91 Capitalized ApiTags 'favorites'
  src/favorites/controllers/favorites.controller.ts
Labels: size: 0.5

#92 Fix reviews
  src/review/controllers/review.controller.ts
  src/review/review.entity.ts
Labels: size: 1

#99 Feature update payment methods documentation
  src/payment-methods/controllers/payment-method.controller.ts
  src/payment-methods/dto/create-payment-method.dto.ts
  src/payment-methods/payment-method.entity.ts
  src/payment-methods/services/payment-method.service.ts
  src/paymentMethods/controllers/payment-method.controller.ts
  src/paymentMethods/payment-method.entity.ts
  src/paymentMethods/payment-method.module.ts
  src/paymentMethods/services/payment-method.service.ts
Labels: documentation, enhancement

#98 Feature 15 shopping cart unit testing
  package-lock.json
  src/account-status/account-status.module.ts
  src/cart/cart.module.ts
  src/cart/controllers/cart.controller.spec.ts
  src/cart/controllers/cart.controller.ts
  src/cart/entities/cart.entity.ts
  src/cart/services/cart.service.spec.ts
  src/cart/services/cart.service.ts
  src/categories/categories/services/categories.service.ts
Labels: enhancement
