Repository RooftopAcademy/rooftend, pull requests merged in 2021-12, with the labels that each got.

#107 Feature 15 shopping cart documentation
  src/cart/controllers/cart.controller.ts
  src/cart/entities/cart.entity.ts
Labels: documentation, enhancement

#135 Feature 113 offers of the day
  src/app.module.ts
  src/items/entities/items.entity.ts
  src/offers/controllers/offers.controller.spec.ts
  src/offers/controllers/offers.controller.ts
  src/offers/dto/promotion-type.dto.ts
  src/offers/entities/offer.entity.ts
  src/offers/offers.module.ts
  src/offers/pipes/promotion-type-validation.pipe.ts
  src/offers/services/offers.service.spec.ts
  src/offers/services/offers.service.ts
Labels: enhancement

#136 Feature 112 lightning offers
  src/cart-item/controllers/cart-item.controller.ts
  src/cart-item/entities/cart-item.entity.ts
  src/cart/controllers/cart.controller.ts
  src/cart/entities/cart.entity.ts
  src/cart/services/cart.service.ts
  src/offers/controllers/offers.controller.spec.ts
  src/offers/controllers/offers.controller.ts
  src/offers/entities/offer.entity.ts
  src/offers/services/offers.service.spec.ts
  src/offers/services/offers.service.ts
Labels: documentation, enhancement

#123 Feature 118 automatic message post purchase
  package.json
  src/app.module.ts
  src/custom-messages/controllers/custom-messages.controller.spec.ts
  src/custom-messages/controllers/custom-messages.controller.ts
  src/custom-messages/custom-messages.module.ts
  src/custom-messages/entities/create-custom-messages.dto.ts
  src/custom-messages/entities/custom-messages.entity.ts
  src/custom-messages/entities/get-custom-messages.dto.ts
  src/custom-messages/entities/update-custom-messages.dto.ts
  src/custom-messages/services/custom-messages.service.spec.ts
  src/custom-messages/services/custom-messages.service.ts
Labels: enhancement

#129 Feature 101 improve favorite module
  src/favorites/controllers/favorites.controller.spec.ts
  src/favorites/controllers/favorites.controller.ts
  src/favorites/dto/create-favorite.dto.ts
  src/favorites/dto/favorite.dto.ts
  src/favorites/entities/favorite.entity.ts
  src/favorites/services/favorites.service.spec.ts
  src/favorites/services/favorites.service.ts
Labels: size: 20

#102 2021 11 26 refactoring documentation
  package-lock.json
  src/platform/controllers/platform.controller.ts
  src/platform/create-platform-dto.entity.ts
  src/platform/platform.entity.ts
  src/platform/services/platform.service.ts
Labels: documentation, enhancement

#104 Fix 103 several fixes paym controller
  src/payment-methods/controllers/payment-method.controller.spec.ts
  src/payment-methods/controllers/payment-method.controller.ts
  src/payment-methods/models/create-payment-method.dto.ts
  src/payment-methods/models/payment-method.entity.ts
  src/payment-methods/payment-method.module.ts
  src/payment-methods/services/payment-method.service.spec.ts
  src/payment-methods/services/payment-method.service.ts
Labels: bug

#138 Feature add payment methods testing
  src/payment-methods/controllers/payment-method.controller.spec.ts
  src/payment-methods/controllers/payment-method.controller.ts
  src/payment-methods/models/create-payment-method.dto.ts
  src/payment-methods/services/payment-method.service.spec.ts
Labels: enhancement

#148 2021 12 14 feature115 purchase
  package-lock.json
  src/cart-item/entities/cart-item.entity.ts
  src/cart/entities/cart.entity.ts
  src/deliveries/entities/delivery-status.enum.ts
  src/deliveries/entities/delivery.entity.ts
  src/items/entities/items.entity.ts
  src/payments/entities/payment-status.enum.ts
  src/payments/entities/payment.entity.ts
  src/platform/entities/platform.entity.ts
  src/purchases/controllers/purchases.controller.spec.ts
  src/purchases/controllers/purchases.controller.ts
  src/purchases/entities/item-details.entity.ts
  src/purchases/entities/purchase-details.entity.ts
  src/purchases/entities/purchase.entity.ts
  src/purchases/purchases.module.ts
  src/purchases/services/purchases.service.spec.ts
  src/purchases/services/purchases.service.ts
Labels: enhancement

#151 fixed route imports
  src/saved-items/controllers/saved-items.controller.ts
  src/saved-items/saved-items.module.ts
  src/saved-items/services/saved-items.service.ts
Labels: bug, size: 0.5

#157 Feature answer module
  src/answers/answers.module.ts
  src/answers/controllers/answers.controller.ts
  src/answers/entities/answer.dto.ts
  src/answers/entities/answer.entity.ts
  src/answers/services/answers.service.ts
  src/app.module.ts
Labels: size: 3

#158 Fix 153 questions
  src/addresses/entities/address.entity.ts
  src/cart/entities/cart.entity.ts
  src/helps/controllers/help.controller.ts
  src/helps/help.entity.ts
  src/helps/help.module.ts
  src/helps/services/help.service.spec.ts
  src/helps/services/help.service.ts
  src/items/entities/items.entity.ts
  src/platform/entities/platform.entity.ts
  src/questions/controllers/questions.controller.ts
  src/questions/entities/question.dto.ts
  src/questions/entities/question.entity.ts
  src/questions/models/questions.entity.ts
  src/questions/models/questions.interface.ts
  src/questions/questions.module.ts
  src/questions/services/questions.service.ts
  src/users/entities/user.entity.ts
Labels: size: 5
