Repository RooftopAcademy/rooftend, pull requests merged in 2022-02, with the labels that each got.

#260 Auth cart items
  src/auth/casl/casl-ability.factory.ts
  src/cart-item/cart-item.module.ts
  src/cart-item/controllers/cart-item.controller.spec.ts
  src/cart-item/controllers/cart-item.controller.ts
  src/cart-item/entities/cart-item.entity.ts
  src/cart-item/entities/create-cart-item.dto.ts
  src/cart-item/entities/update-cart-item.dto.ts
  src/cart-item/services/cart-item.service.spec.ts
  src/cart-item/services/cart-item.service.ts
  src/cart/cart.module.ts
  src/cart/services/cart.service.ts
  src/items/items.module.ts
Labels: documentation, enhancement

#261 Reformat reviews
  src/auth/casl/casl-ability.factory.ts
  src/cart-item/cart-item.module.ts
  src/cart-item/controllers/cart-item.controller.ts
  src/cart-item/services/cart-item.service.ts
  src/cart/services/cart.service.spec.ts
  src/cart/services/cart.service.ts
  src/items/entities/items.entity.ts
  src/items/items.module.ts
  src/review/DTOs/itemReview.create.dto.ts
  src/review/DTOs/like.dto.ts
  src/review/DTOs/userReview.create.dto.ts
  src/review/controllers/itemReviews.controller.ts
  src/review/controllers/likes.controller.ts
  src/review/controllers/review.controller.spec.ts
  src/review/controllers/review.controller.ts
  src/review/controllers/userReviews.controller.ts
  src/review/entities/itemReviews.entity.ts
  src/review/entities/likes.entity.ts
  src/review/entities/reviews.ts
  src/review/entities/userReviews.entity.ts
  src/review/enum/opinions.enum.ts
  src/review/repositories/review.repository.ts
  src/review/review.entity.ts
  src/review/review.module.ts
  src/review/services/itemReviews.service.ts
  src/review/services/likes.service.ts
  src/review/services/review.service.spec.ts
  src/review/services/review.service.ts
  src/review/services/userReviews.service.ts
  src/users/entities/user.entity.ts
  src/users/services/user.service.spec.ts
Labels: size: 20

#244 Improved shipping methods module
  src/shipping-methods/controllers/shipping-methods.controller.ts
  src/shipping-methods/dto/shipping-method.dto.ts
  src/shipping-methods/services/shipping-methods.service.spec.ts
  src/shipping-methods/services/shipping-methods.service.ts
Labels: documentation
