Repository RooftopAcademy/rooftend, pull requests merged in 2022-01, with the labels that each got.

#164 Fix questions answers modules
  src/answers/answers.module.ts
  src/answers/controllers/answers.controller.ts
  src/answers/services/answers.service.ts
  src/app.module.ts
  src/questions/controllers/questions.controller.spec.ts
  src/questions/controllers/questions.controller.ts
  src/questions/entities/answer.dto.ts
  src/questions/entities/answer.entity.ts
  src/questions/entities/create-question-dto.ts
  src/questions/entities/question.dto.ts
  src/questions/entities/question.entity.ts
  src/questions/questions.module.ts
  src/questions/services/answers.service.spec.ts
  src/questions/services/answers.service.ts
  src/questions/services/questions.service.spec.ts
  src/questions/services/questions.service.ts
  src/statusCodes/status.interface.ts
  src/statusCodes/statusCodes.ts
  src/users/controllers/user.controller.spec.ts
Labels: size: 20

#167 Módulo de autorización
  package.json
  src/app.module.ts
  src/auth/casl/casl-ability.factory.spec.ts
  src/auth/casl/casl-ability.factory.ts
  src/auth/casl/casl.module.ts
  src/auth/guards/policies.guard.spec.ts
  src/auth/guards/policies.guard.ts
  src/auth/permission.enum.ts
  src/auth/policy-handler.ts
Labels: enhancement, size: 8

#194 Fix 161 offers module
  src/offers/controllers/offers.controller.spec.ts
  src/offers/controllers/offers.controller.ts
  src/offers/controllers/price-order.enum.ts
  src/offers/controllers/price-range-validation.pipe.ts
  src/offers/controllers/promotion-type-validation.pipe.ts
  src/offers/dto/offer.dto.ts
  src/offers/dto/price-range.dto.ts
  src/offers/dto/promotion-type.dto.ts
  src/offers/entities/offer.entity.ts
  src/offers/entities/promotion-type.enum.ts
  src/offers/services/offers.service.spec.ts
  src/offers/services/offers.service.ts
Labels: bug, documentation, enhancement

#193 Remove unnecesary shipping methods
  src/shipping-methods/controllers/shipping-methods.controller.spec.ts
  src/shipping-methods/controllers/shipping-methods.controller.ts
  src/shipping-methods/services/shipping-methods.service.spec.ts
  src/shipping-methods/services/shipping-methods.service.ts
  src/shipping-methods/shipping-methods.module.ts
Labels: size: 0.5

#203 Generic Type
  src/auth/casl/casl-ability.factory.ts
  src/auth/types/flat-class.type.ts
Labels: enhancement

#204 Auth folder structure
  src/auth/casl/casl-ability.factory.ts
  src/auth/constants/check-policies.constant.ts
  src/auth/enums/permission.enum.ts
  src/auth/guards/policies.guard.ts
  src/auth/types/flat-class.type.ts
  src/auth/types/policy-handler.type.ts
  src/items/controllers/items.controller.spec.ts
  src/items/entities/items.entity.ts
  src/items/services/items.service.spec.ts
  src/items/services/items.service.ts
Labels: size: 0.5

#201 Fix swagger documentation
  src/addresses/entities/address.entity.ts
  src/brands/controllers/brands.controllers.ts
  src/brands/entities/brands.entity.ts
  src/brands/entities/create-brands-dto.entity.ts
  src/brands/mock/brands.ts
  src/cart-item/entities/cart-item.entity.ts
  src/cart/entities/cart.entity.ts
  src/categories/entities/categories.entity.ts
  src/categories/mock/categories.ts
  src/history/models/history.entity.ts
  src/items/entities/items.entity.ts
  src/phones/controllers/phones.controller.ts
  src/phones/entities/phone.entity.ts
  src/photos/models/photos.entity.ts
  src/platform/entities/platform.entity.ts
  src/questions/controllers/questions.controller.ts
  src/questions/entities/question.entity.ts
  src/questions/services/questions.service.ts
  src/saved-items/dto/CreateSavedItemDto.ts
  src/saved-items/entities/SavedItems.entity.ts
  src/search/search.entity.ts
  src/stores/controllers/stores.controller.ts
  src/support/entities/supportCategory.entity.ts
  src/support/entities/supportQuestion.entity.ts
  src/support/entities/supportRequest.entity.ts
  src/users/entities/user.entity.ts
Labels: size: 13

#213 Fix swagger documentation
  src/addresses/entities/address.entity.ts
  src/brands/controllers/brands.controllers.ts
  src/cart-item/entities/cart-item.entity.ts
  src/cart-item/entities/create-cart-item.dto.ts
  src/cart/entities/cart.entity.ts
  src/custom-messages/entities/custom-messages.entity.ts
  src/deliveries/entities/delivery.entity.ts
  src/favorites/entities/favorite.entity.ts
  src/history/models/history.entity.ts
  src/items/entities/items.entity.ts
  src/offers/entities/offer.entity.ts
  src/payment-methods/controllers/payment-method.controller.ts
  src/payment-methods/models/payment-method.entity.ts
  src/payments/entities/payment.entity.ts
  src/phones/controllers/phones.controller.ts
  src/phones/entities/phone.entity.ts
  src/photos/controllers/photos.controller.ts
  src/photos/models/photos.entity.ts
  src/platform/controllers/platform.controller.ts
  src/platform/entities/platform.entity.ts
  src/platform/entities/update-platform-dto.entity.ts
  src/profile/controllers/profile.controller.spec.ts
  src/profile/controllers/profile.controller.ts
  src/profile/controllers/profiles.controller.ts
  src/profile/entities/profile.entity.ts
  src/profile/mock/profiles.ts
  src/profile/profile.entity.ts
  src/profile/profile.module.ts
  src/profile/services/profile.service.spec.ts
  src/profile/services/profile.service.ts
  src/purchases/entities/item-details.entity.ts
  src/questions/controllers/questions.controller.ts
  src/questions/entities/question.entity.ts
  src/questions/services/questions.service.ts
  src/saved-items/dto/UpdateSavedItemDto.ts
  src/saved-items/entities/SavedItems.entity.ts
  src/search/entities/search.entity.ts
  src/search/search.module.ts
  src/search/services/search.service.spec.ts
  src/search/services/search.service.ts
  src/stores/controllers/stores.controller.ts
  src/stores/entities/create-store.dto.ts
  src/stores/entities/read-store.dto.ts
  src/stores/entities/stores.entity.ts
  src/stores/services/stores.service.spec.ts
  src/stores/services/stores.service.ts
  src/stores/stores.module.ts
  src/support/controllers/support.controller.ts
  src/support/entities/supportCategory.entity.ts
  src/support/entities/supportQuestion.entity.ts
  src/support/entities/supportRequest.entity.ts
  src/users/entities/user.entity.ts
Labels: size: 0

#214 Fixed default dates.
  src/addresses/entities/address.entity.ts
  src/cart-item/entities/cart-item.entity.ts
  src/cart/entities/cart.entity.ts
  src/custom-messages/entities/custom-messages.entity.ts
  src/deliveries/entities/delivery.entity.ts
  src/favorites/entities/favorite.entity.ts
  src/history/models/history.entity.ts
  src/items/entities/items.entity.ts
  src/offers/entities/offer.entity.ts
  src/payment-methods/models/payment-method.entity.ts
  src/payments/entities/payment.entity.ts
  src/photos/models/photos.entity.ts
  src/platform/entities/platform.entity.ts
  src/platform/entities/update-platform-dto.entity.ts
  src/questions/entities/question.entity.ts
  src/search/entities/search.entity.ts
  src/stores/entities/stores.entity.ts
  src/support/entities/supportCategory.entity.ts
  src/support/entities/supportQuestion.entity.ts
  src/support/entities/supportRequest.entity.ts
Labels: bug

#212 Fix 211 shipping methods module
  src/shipping-methods/controllers/shipping-methods.controller.ts
  src/shipping-methods/dto/shipping-method.dto.ts
  src/shipping-methods/entities/shipping-method.entity.ts
  src/shipping-methods/services/shipping-methods.service.ts
Labels: bug, documentation

#216 Refactored default dates
  src/addresses/entities/address.entity.ts
  src/cart-item/entities/cart-item.entity.ts
  src/cart/entities/cart.entity.ts
  src/custom-messages/entities/custom-messages.entity.ts
  src/deliveries/entities/delivery.entity.ts
  src/favorites/entities/favorite.entity.ts
  src/history/models/history.entity.ts
  src/items/entities/items.entity.ts
  src/offers/entities/offer.entity.ts
  src/payment-methods/models/payment-method.entity.ts
  src/payments/entities/payment.entity.ts
  src/photos/models/photos.entity.ts
  src/platform/entities/platform.entity.ts
  src/platform/entities/update-platform-dto.entity.ts
  src/questions/entities/question.entity.ts
  src/search/entities/search.entity.ts
  src/stores/entities/stores.entity.ts
  src/support/entities/supportCategory.entity.ts
  src/support/entities/supportQuestion.entity.ts
  src/support/entities/supportRequest.entity.ts
Labels: documentation, size: 2

#221 Fix refactor
  src/cart-item/services/cart-item.service.ts
  src/phones/services/phones.service.ts
  src/review/controllers/review.controller.ts
  tsconfig.json
Labels: bug, size: 0.5

#231 Fix public decorator
  src/authentication/guards/jwt-auth.guard.ts
  src/authentication/strategies/local.strategy.ts
Labels: bug

#235 Create new service method for registry controller
  src/authentication/controllers/authentication.controller.ts
  src/authentication/services/authentication.service.ts
Labels: bug

#237 Auth items fix
  src/items/controllers/items.controller.spec.ts
  src/items/controllers/items.controller.ts
  src/items/entities/items.entity.ts
  src/items/services/items.service.spec.ts
  src/items/services/items.service.ts
Labels: enhancement

#205 Auth custom messages
  src/auth/casl/casl-ability.factory.ts
  src/custom-messages/controllers/custom-messages.controller.spec.ts
  src/custom-messages/controllers/custom-messages.controller.ts
  src/custom-messages/custom-messages.module.ts
  src/custom-messages/entities/create-custom-messages.dto.ts
  src/custom-messages/entities/custom-messages.entity.ts
  src/custom-messages/entities/get-custom-messages.dto.ts
  src/custom-messages/entities/update-custom-messages.dto.ts
  src/custom-messages/services/custom-messages.service.spec.ts
  src/custom-messages/services/custom-messages.service.ts
Labels: enhancement

#236 Cart authorization
  src/app.module.ts
  src/auth/casl/casl-ability.factory.ts
  src/cart/cart.module.ts
  src/cart/controllers/cart.controller.spec.ts
  src/cart/controllers/cart.controller.ts
  src/cart/entities/cart.entity.ts
  src/cart/services/cart.service.spec.ts
  src/cart/services/cart.service.ts
Labels: enhancement

#239 Auth items fix entity
  src/items/entities/items.entity.ts
Labels: bug

#250 2022 01 19 refactor auth add mail
  src/authentication/controllers/authentication.controller.ts
  src/authentication/services/authentication.service.ts
Labels: enhancement

#251 Changed @Column decorator for @CreateDateColumn
  src/message-post-purchases/entities/message-post-purchase.entity.ts
Labels: size: 0

#257 Refactor user registration
  src/authentication/services/authentication.service.ts
  src/cart/services/cart.service.ts
Labels: bug, enhancement
